version: '3.9'
services:
  post_service:
    container_name: post_service
    environment:
      - SERVER_PORT=${POST_SVC_PORT}
      - DB_USER=${POST_SVC_DB_USER}
      - DB_PASSWORD=${POST_SVC_DB_PASSWORD}
      - DB_NAME=${POST_SVC_DB_NAME}
      - DB_HOST=${POST_SVC_DB_HOST}
      - DB_PORT=${POST_SVC_DB_PORT}
    tty: true
    build: ./post_service
    ports:
      - "${POST_SVC_PORT}:${POST_SVC_PORT}"
    restart: on-failure
    volumes:
      - ./post_service:/app
    depends_on:
      - post_db
    networks:
      - social_network

  post_db:
    image: postgres:latest
    container_name: post_db
    environment:
      - POSTGRES_USER=${POST_SVC_DB_USER}
      - POSTGRES_PASSWORD=${POST_SVC_DB_PASSWORD}
      - POSTGRES_DB=${POST_SVC_DB_NAME}
      - DATABASE_HOST=${POST_SVC_DB_HOST}
    ports:
      - "1234:5432"
    volumes:
      - ./post_service/post_svc_data:/var/lib/postgresql/data
    networks:
      - social_network

  follower_service:
    container_name: follower_service
    environment:
      - SERVER_PORT=${FOLLOWER_SVC_PORT}
      - DB_URI=${FOLLOWER_DB_URI}
      - DB_USER=${FOLLOWER_DB_USER}
      - DB_PASSWORD=${FOLLOWER_DB_PASSWORD}
    tty: true
    build: ./follower_service
    ports:
      - "${FOLLOWER_SVC_PORT}:${FOLLOWER_SVC_PORT}"
    restart: on-failure
    volumes:
      - ./follower_service:/app
    depends_on:
      - follower_db
    networks:
      - social_network

  follower_db:
    image: neo4j:5.15.0
    container_name: follower_db
    environment: 
      - NEO4J_AUTH=${FOLLOWER_DB_USER}/${FOLLOWER_DB_PASSWORD}
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./follower_service/follower_db:/data
    networks:
      - social_network

volumes:
  post_svc_data:
  follower_db:

networks:
  social_network:
    driver: bridge