services:
  post_service:
    container_name: post_service
    environment:
      - SERVER_PORT=${POST_SVC_PORT}
      - DB_USER=${POST_SVC_DB_USER}
      - DB_PASSWORD=${POST_SVC_DB_PASSWORD}
      - DB_NAME=${POST_SVC_DB_NAME}
      - DB_HOST=${POST_SVC_DB_HOST}
      - DB_PORT=${POST_SVC_DB_PORT}
    tty: true
    build: ./post_service
    ports:
      - "${POST_SVC_PORT}:${POST_SVC_PORT}"
    restart: on-failure
    volumes:
      - ./post_service:/app
    depends_on:
      - post_db
    networks:
      - social_network

  post_db:
    image: postgres:latest
    container_name: post_db
    environment:
      - POSTGRES_USER=${POST_SVC_DB_USER}
      - POSTGRES_PASSWORD=${POST_SVC_DB_PASSWORD}
      - POSTGRES_DB=${POST_SVC_DB_NAME}
      - DATABASE_HOST=${POST_SVC_DB_HOST}
    ports:
      - "1234:5432"
    volumes:
      - ./post_service/post_svc_data:/var/lib/postgresql/data
    networks:
      - social_network

  follower_service:
    container_name: follower_service
    environment:
      - SERVER_PORT=${FOLLOWER_SVC_PORT}
      - DB_URI=${FOLLOWER_DB_URI}
      - DB_USER=${FOLLOWER_DB_USER}
      - DB_PASSWORD=${FOLLOWER_DB_PASSWORD}
    tty: true
    build: ./follower_service
    ports:
      - "${FOLLOWER_SVC_PORT}:${FOLLOWER_SVC_PORT}"
    restart: on-failure
    volumes:
      - ./follower_service:/app
    depends_on:
      - follower_db
    networks:
      - social_network

  follower_db:
    image: neo4j:5.15.0
    container_name: follower_db
    environment: 
      - NEO4J_AUTH=${FOLLOWER_DB_USER}/${FOLLOWER_DB_PASSWORD}
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./follower_service/follower_db:/data
    networks:
      - social_network

  user_service:
    container_name: user_service
    environment:
      - SERVER_PORT=${USER_SVC_PORT}
      - MONGODB_URI=mongodb://${USER_DB_ROOT_USERNAME}:${USER_DB_ROOT_PASSWORD}@user_db
    tty: true
    build: ./user_service
    ports:
      - "${USER_SVC_PORT}:${USER_SVC_PORT}"
    restart: on-failure
    volumes:
      - ./user_service:/app
    depends_on:
      - user_db
    networks:
      - social_network

  user_db:
    container_name: user_db
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USER_DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${USER_DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${USER_DB_NAME}
    restart:
      always
    volumes:
      - ./user_service/user_db:/data
    ports:
      - "12345:27017"
    networks:
      - social_network

  feed_service:
    container_name: feed_service
    environment:
      - SERVER_PORT=${FEED_SVC_PORT}
      - REDIS_URL=redis://${FEED_DB_USER}:${FEED_DB_PASSWORD}@feed_db
      - FOLLOWER_SVC_PORT=${FOLLOWER_SVC_PORT}
      - POST_SVC_PORT=${POST_SVC_PORT}
    tty: true
    build: ./feed_service
    ports:
      - "${FEED_SVC_PORT}:${FEED_SVC_PORT}"
    restart: on-failure
    volumes:
      - ./feed_service:/app
    depends_on:
      - feed_db
    networks:
      - social_network
  
  feed_db:
    container_name: feed_db
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${FEED_DB_PASSWORD}
    volumes: 
      - ./feed_service/feed_db:/data
    networks:
      - social_network

volumes:
  post_svc_data:
  follower_db:
  user_db:
  feed_db:
    driver: local

networks:
  social_network:
    driver: bridge